name: Github build stats
description: "Get Build Stats in GitHub Actions workflow."
branding:
  icon: check-circle
  color: green
inputs:
  GITHUB_TOKEN:
    description: 'Github token to access the build stats. repo access should be good enough '
    required: true
  GITHUB_ORG_ID:
    description: 'The organization id where your repository is located. It might be your username, company name, etc'
    required: true
  GITHUB_REPOSITORY_ID:
    description: 'The repo id that we with to get stats from its workflow'
    required: true
    default: ${{ github.event.repository.name }}
  GITHUB_RUN_ID:
    description: 'The run id that we wish to get stats from'
    required: true
    default: ${{ github.run_id }}

outputs:
  output:
    value:
    description: "Output from the action"

runs:
  using: 'composite'
  steps:
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - uses: actions/checkout@v3
        with:
          repository: 'SallyBlichG/github-build-stats'
          ref: 'main'

      - name: Install Dependencies
        run: sudo apt install libcurl4-openssl-dev libssl-dev && pip install -r requirements.txt
        shell: bash

      - name: Pass Inputs to Shell
        run: |
          echo "GITHUB_TOKEN=${{ inputs.GITHUB_TOKEN }}" >> $GITHUB_ENV
          echo "GITHUB_REPOSITORY_ID=${{ inputs.GITHUB_REPOSITORY_ID }}" >> $GITHUB_ENV
          echo "GITHUB_RUN_ID=${{ inputs.GITHUB_RUN_ID }}" >> $GITHUB_ENV
          echo "GITHUB_ORG_ID=${{ inputs.GITHUB_ORG_ID }}" >> $GITHUB_ENV
        shell: bash

      - name: Run python script, action stats
        id: get-stats
        run: python src/main.py
        shell: bash